#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Constants/settings definition
"""

LANGS_TO_KEEP = 50
CUISINES_TO_KEEP = 50

# 12 12 5000
THRESHOLD_MIN_CUISINES = 12
THRESHOLD_MIN_LANGUAGES = 12
THRESHOLD_MIN_VOICE_LENGTH = 5000

Y_REPLACE_LANGUAGES_ABBREVIATIONS = True
X_ADD_CUISINE = False
Y_ADD_LANGUAGE = False
X_ADD_FLAGS = True
Y_ADD_FLAGS = True

AXIS_ANNOTATION_TEXT_SIZE = 16
