#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Constants/settings definition
"""

LANGS_TO_KEEP = 50
CUISINES_TO_KEEP = 50

THRESHOLD_MIN_CUISINES = 12
THRESHOLD_MIN_LANGUAGES = 12
THRESHOLD_MIN_VOICE_LENGTH = 5000

REPLACE_LANGUAGES_ABBREVIATIONS = True
ADD_CUISINE_TO_XLABELS = True
ADD_CUISINES_COUNTRY_FLAG = False
